// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnnualFormController from "./annual_form_controller.js"
application.register("annual-form", AnnualFormController)

import GeolocationController from "./geolocation_controller.js"
application.register("geolocation", GeolocationController)

import TopNavController from "./top_nav_controller.js"
application.register("top-nav", TopNavController)
